language: ruby
rvm:
 - 2.6
addons:
  ssh_known_hosts:
  - marii.hosting.nyu.edu
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script:
  - bundle exec jekyll build -d _site/gitsite
  - bundle exec rake test
after_success:
  - rm -rf _site && bundle exec jekyll build
  - bundle exec rake deploy
