language: ruby
rvm:
 - 2.6
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script:
  - bundle exec jekyll build -d _site/gitsite
  - bundle exec rake test
after_success:
  - rm -rf _site && bundle exec jekyll build
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
  - bundle exec rake deploy
